jobs:
  Feedback-Provided:
    if: github.repository_owner == 'spring-projects' && github.event_name == 'issue_comment'
      && github.event.action == 'created' && github.actor != 'spring-projects-issues'
      && github.event.pull_request == null && github.event.issue.state == 'open' &&
      contains(toJSON(github.event.issue.labels), 'waiting-for-feedback')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Update Project Card
      uses: peter-evans/create-or-update-project-card@v1.1.2
      with:
        column-name: Feedback provided
        project-location: spring-projects
        project-name: Spring Data
        token: ${{ secrets.GH_ISSUES_TOKEN_SPRING_DATA }}
  Inbox:
    if: github.repository_owner == 'spring-projects' && (github.event.action == 'opened'
      || github.event.action == 'reopened') && github.event.pull_request == null
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Create or Update Issue Card
      uses: peter-evans/create-or-update-project-card@v1.1.2
      with:
        column-name: Inbox
        project-location: spring-projects
        project-name: Spring Data
        token: ${{ secrets.GH_ISSUES_TOKEN_SPRING_DATA }}
  Pull-Request:
    if: github.repository_owner == 'spring-projects' && (github.event.action == 'opened'
      || github.event.action == 'reopened') && github.event.pull_request != null
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Create or Update Pull Request Card
      uses: peter-evans/create-or-update-project-card@v1.1.2
      with:
        column-name: Review pending
        issue-number: ${{ github.event.pull_request.number }}
        project-location: spring-projects
        project-name: Spring Data
        token: ${{ secrets.GH_ISSUES_TOKEN_SPRING_DATA }}
name: Spring Data GitHub Issues
on:
  repository_dispatch:
    types: trigger-ga___project.yml
